# Generated by Django 4.2 on 2023-04-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('competition_type', models.CharField(choices=[('League', 'Лига'), ('Single', 'Олимпийская система'), ('Double', 'Двойной отбор')], max_length=30)),
                ('number_of_participants', models.IntegerField()),
                ('list_of_participants', models.CharField(max_length=10000)),
                ('logotype', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
