# Generated by Django 4.2 on 2023-04-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing_tables', '0002_rename_tables_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='number_of_participants',
        ),
    ]
