# Generated by Django 4.2 on 2023-04-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_tables', '0003_remove_table_number_of_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='number_of_points_for_a_win',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
