# Generated by Django 4.2 on 2023-04-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_tables', '0004_table_number_of_points_for_a_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='competition_type',
            field=models.CharField(choices=[('Лига', 'Лига'), ('Олимпийская система', 'Олимпийская система'), ('Двойной отбор', 'Двойной отбор')], max_length=30),
        ),
        migrations.AlterField(
            model_name='table',
            name='number_of_points_for_a_win',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
