# Generated by Django 4.2 on 2023-04-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_tables', '0005_alter_table_competition_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='list_of_participants',
            field=models.CharField(max_length=3500),
        ),
    ]
