# Generated by Django 4.2 on 2023-05-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_tables', '0007_table_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='logotype',
            field=models.ImageField(blank=True, upload_to='managing_tables/images'),
        ),
    ]
