# Generated by Django 4.2 on 2023-05-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing_tables', '0009_remove_table_list_of_participants_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
