# Generated by Django 4.2 on 2023-05-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing_tables', '0012_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
    ]
