# Generated by Django 4.2 on 2023-05-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managing_tables', '0013_remove_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='managing_tables.table'),
            preserve_default=False,
        ),
    ]
