# Generated by Django 4.2 on 2023-05-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_tables', '0014_match_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match',
            field=models.ManyToManyField(limit_choices_to=2, to='managing_tables.participant'),
        ),
    ]
