# Generated by Django 4.2 on 2023-05-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing_tables', '0015_alter_match_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='table',
        ),
    ]
