# Generated by Django 4.2 on 2023-05-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_tables', '0016_remove_match_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match',
            field=models.ManyToManyField(to='managing_tables.participant'),
        ),
    ]
