# Generated by Django 4.2 on 2023-05-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_tables', '0017_alter_match_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
