# Generated by Django 4.2 on 2023-05-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_tables', '0018_match_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='competition_type',
            field=models.CharField(choices=[('Лига', 'Лига'), ('Олимпийская система', 'Олимпийская система')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
