# Generated by Django 4.2 on 2023-05-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_tables', '0019_alter_table_competition_type_delete_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='competition_type',
            field=models.CharField(choices=[('Лига', 'Лига'), ('Олимпийская система', 'Олимпийская система'), ('Двойной отбор', 'Двойной отбор')], max_length=30),
        ),
    ]
