# Generated by Django 4.2 on 2023-05-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_tables', '0020_alter_table_competition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
    ]
