# Generated by Django 4.2 on 2023-05-05 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing_tables', '0021_table_privacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='looses',
            new_name='defeats',
        ),
    ]
